[tools]
aws-cli = "latest"
helm = "3.16.3"
java = "temurin-17"
kubectl = "1.30.6"
"pipx:tox" = "latest"
pre-commit = "latest"
python = "latest"
rust = "latest"
sbt = "latest"
sops = "latest"
terraform = "latest"
tflint = "latest"
"ubi:aolwas/adt" = "latest"
"ubi:aolwas/aws-token-rotate" = "latest"
"ubi:skim-rs/skim" = { version = "latest", exe = "sk" }
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = []

[settings.python]
compile = false
