#!/usr/bin/env bash

# Original script: https://github.com/jvanbruegge/dotfiles/blob/master/sway/wifi/nmcli-rofi

# supported locales (en, ru, de, fr, hi, ja)
declare -A LOC_ACTIVE=(["en"]="yes" ["de"]="ja")
declare -A LOC_INACTIVE=(["en"]="no" ["de"]="nein")

# get current locale
CURRLOCALE=$(locale | grep 'LANG=[a-z]*' -o | sed 's/^LANG=//g')
# 'enabled' in currnet locale
ACTIVE="${LOC_ACTIVE["$CURRLOCALE"]}"
INACTIVE="${LOC_INACTIVE["$CURRLOCALE"]}"

function vpn_list () {
    nmcli --fields ACTIVE,NAME,TYPE con | awk '{ if ($NF == "vpn") { print "VPN: "$0 } }' | sed 's/ *vpn *$/"/g' | \
        sed "s/ *$INACTIVE */ Connect to \"/g" | sed "s/ *$ACTIVE */ Disconnect from \"/g"
}

function rofi_cmd () {
  # don't repeat lines with uniq -u
  echo -e "$1" | uniq -u | wofi --show dmenu --insensitive -p "VPN Connections" --cache /dev/null
}

function rofi_menu () {
    VPNLIST="$(vpn_list)"

    rofi_cmd "$VPNLIST"
}

function main () {
    OPS=$(rofi_menu)

    if [ -z "$OPS" ]; then
      exit 0
    fi

    if [[ "$OPS" == "VPN: "* ]]; then
      name=$(echo "$OPS"  | cut -d'"' -f 2)
      if [[ "$OPS" =~ "Connect" ]]; then
        echo "Connect VPN $name"
        nmcli connection up "$name"
      else
        echo "Disconnect VPN $name"
        nmcli connection down "$name"
      fi
    fi
}

# clean up obsoleted connections
# nmcli --fields UUID,TIMESTAMP-REAL,DEVICE con show | grep never |  awk '{print $1}' | while read line; do nmcli con delete uuid $line; done

main
